#!/bin/sh
# $Id: mk,v 1.3 2016-10-06 16:12:04-07 - - $
FILES='astree.h     astree.cpp
       auxlib.h     auxlib.cpp
       lyutils.h    lyutils.cpp
       string_set.h string_set.cpp
       yyparse.h    parser.y'
bison --defines=yyparse.h --output=yyparse.cpp parser.y
cid + $FILES
COMPILECPP='g++ -std=gnu++17 -g -O0 -Wall -Wextra'
$COMPILECPP -c -fsyntax-only *.cpp
mkpspdf Listing.ps $FILES
