# Makefile.deps created Sun Apr 28 15:13:16 PDT 2019 by make
astree.o: astree.cpp astree.h auxlib.h string_set.h lyutils.h yyparse.h
lyutils.o: lyutils.cpp auxlib.h lyutils.h astree.h string_set.h yyparse.h
string_set.o: string_set.cpp auxlib.h string_set.h
auxlib.o: auxlib.cpp auxlib.h
main.o: main.cpp string_set.h auxlib.h lyutils.h astree.h yyparse.h
yylex.o: yylex.cpp lyutils.h astree.h auxlib.h string_set.h yyparse.h
yyparse.o: yyparse.cpp lyutils.h astree.h auxlib.h string_set.h yyparse.h
