# Makefile.deps created Sat 04 May 2019 09:21:36 PM PDT by make
astree.o: astree.cpp astree.h auxlib.h string_set.h lyutils.h yyparse.h
lyutils.o: lyutils.cpp auxlib.h lyutils.h astree.h string_set.h yyparse.h
string_set.o: string_set.cpp auxlib.h string_set.h
auxlib.o: auxlib.cpp auxlib.h
main.o: main.cpp string_set.h auxlib.h lyutils.h astree.h yyparse.h
yylex.o: yylex.cpp lyutils.h astree.h auxlib.h string_set.h yyparse.h
yyparse.o: yyparse.cpp astree.h auxlib.h lyutils.h string_set.h yyparse.h
